pipeline {
    // agent {
    //     label 'AGENT-1'
    // }
    options {
        timeout(time: 30, unit: 'SECONDS') //
        disableConcurrentBuilds() // disable concurrent builds on this job
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    environment{
        DEPLOY_TO =  'production'
        GREETING = 'Good Morning'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo This is build'
                sh 'env'
            }
        }
        stage('Test') {
            steps {
                sh 'echo This is Test'
            }
        }
        stage('Deploy') {
            steps {
                input {
                    message "is it ok to deploy?"
                    ok "yes, we can do"
                }
                sh 'echo This is Deploy'
            }
        }
        stage("print params"){
            steps{
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
                //echo "triggered test again"
                //error 'some failure'
            }
        }
        stage("when condition one"){
            when {
                expression{
                    params.action == 'One'
                }
            }
            steps{
                echo "This is one condition"
                
                //echo "triggered test again"
                //error 'some failure'
            }
        }
        stage("when condition Two"){
            when {
                expression{
                    params.action == 'two'
                }
            }
            steps{
                echo "This is two condition"
                
                //echo "triggered test again"
                //error 'some failure'
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }
    }
}